---
inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
RSpec/MultipleMemoizedHelpers:
  Max: 7
RSpec/NamedSubject:
  Enabled: false
RSpec/NestedGroups:
  Max: 5
